In [2]:
import pandas as pd
import numpy as np

In [ ]:
cards = pd.read_csv('C:\\Users\\Abdul\\Downloads\\Banking project\\cards.csv')

In [6]:
users = pd.read_csv('C:\\Users\\Abdul\\Downloads\\Banking project\\users.csv')

In [7]:
transactions = pd.read_csv('C:\\Users\\Abdul\\Downloads\\Banking project\\transactions.csv')

In [84]:
cards['Credit Limit'] = cards['Credit Limit'].str.replace('$','',regex=False).astype(int)

### Cards analysis

#### Which card type is most commonly used?

In [85]:
res = cards['Card Type'].value_counts().reset_index(name = 'count')
res.index = res.index + 1
res['count'] = res['count'].apply(lambda x : f"{x:,.0f}")
res

         Card Type  count
1            Debit  3,511
2           Credit  2,057
3  Debit (Prepaid)    578

#### Which card brand is most commonly used?

In [86]:
res = cards['Card Brand'].value_counts().reset_index(name = 'count')
res.index = res.index + 1
res['count'] = res['count'].apply(lambda x : f"{x:,.0f}")
res

   Card Brand  count
1  Mastercard  3,209
2        Visa  2,326
3        Amex    402
4    Discover    209

#### How many cards in dark web?

In [80]:
cards[cards['Card on Dark Web'] == 'yes']

Empty DataFrame
Columns: [User, CARD INDEX, Card Brand, Card Type, Card Number, Expires, CVV, Has Chip, Cards Issued, Credit Limit, Acct Open Date, Year PIN last Changed, Card on Dark Web]
Index: []

#### what's the total card limit by card type?

In [87]:
res = cards.groupby('Card Type')['Credit Limit'].sum().reset_index(name = 'Total')
res.index = res.index + 1 
res['Total'] = res['Total'].apply(lambda x : f"{x:,.0f} $")
res

         Card Type         Total
1           Credit  22,985,700 $
2            Debit  65,156,747 $
3  Debit (Prepaid)      37,251 $

#### what's the total card limit by card brand?

In [88]:
res = cards.groupby('Card Brand')['Credit Limit'].sum().reset_index(name='Total')

res = res.sort_values(by='Total', ascending=False).reset_index(drop=True)

res.index = res.index + 1

res['Total'] = res['Total'].apply(lambda x: f"{x:,.0f} $")

res

   Card Brand         Total
1  Mastercard  47,042,657 $
2        Visa  34,279,041 $
3        Amex   4,597,400 $
4    Discover   2,260,600 $

### Users analysis

#### How many users?

In [103]:
users['Person'].count()

np.int64(2000)

#### How many users by age?

In [113]:
res = users['Current Age'].value_counts().reset_index(name = 'count').sort_values(by = 'count',ascending=False)
res.index = res.index + 1
res

    Current Age  count
1            18     77
2            47     47
3            49     44
5            50     43
4            22     43
..          ...    ...
76           98      2
77           94      2
78          101      1
79           93      1
80           99      1

[80 rows x 2 columns]

#### How many users by gender?

In [115]:
res = users['Gender'].value_counts().reset_index(name = 'count').sort_values(by = 'count',ascending=False)
res.index = res.index + 1
res

   Gender  count
1  Female   1016
2    Male    984

#### How many users by city?

In [116]:
res = users['City'].value_counts().reset_index(name = 'count').sort_values(by = 'count',ascending=False)
res.index = res.index + 1
res

               City  count
1           Houston     22
2           Chicago     18
3       Los Angeles     16
4             Miami     14
5          Brooklyn     12
...             ...    ...
650         Perkins      1
651     Crown Point      1
652     North Haven      1
653   Honeoye Falls      1
1286      Merrimack      1

[1286 rows x 2 columns]

#### How many users by state?

In [117]:
res = users['State'].value_counts().reset_index(name = 'count').sort_values(by = 'count',ascending=False)
res.index = res.index + 1
res

   State  count
1     CA    244
2     TX    159
3     FL    131
4     NY    125
5     IL     87
6     OH     86
7     PA     84
8     NC     78
9     GA     65
10    MI     60
11    NJ     54
12    TN     51
13    IN     48
14    WA     44
15    VA     43
16    MA     40
17    MD     39
18    WI     34
19    AL     33
20    AZ     33
21    KY     32
22    SC     31
23    LA     30
24    OK     29
25    MO     29
26    IA     26
27    MN     25
28    CO     23
29    OR     22
30    CT     22
31    MS     18
32    AR     18
33    KS     18
34    NM     14
35    NH     13
36    NV     13
37    UT     12
40    HI     10
39    NE     10
38    WV     10
41    RI      8
42    DE      7
43    ID      7
44    ME      7
45    SD      6
46    MT      6
47    VT      6
48    ND      5
49    AK      2
50    WY      2
51    DC      1

#### What's the total dept by gender?

In [76]:
res = users.groupby('Gender')['Total Debt'].sum()
res = res.reset_index(name = 'Total').sort_values(by = 'Total',ascending=False)
res.index = res.index + 1
res['Total'] = res['Total'].apply(lambda x : f"{x:,.0f}")
res

   Gender       Total
1  Female  64,331,433
2    Male  63,087,955

#### What's the total dept by city?

In [72]:
res = users.groupby('City')['Total Debt'].sum().reset_index(name = 'Total')
res = res.sort_values(by = 'Total',ascending=False).reset_index(drop=True)
res.index = res.index + 1
res['Total'] = res['Total'].apply(lambda x : f"{x:,.0f}")
res

                        City      Total
1                    Houston  1,805,804
2                      Miami  1,045,937
3                Los Angeles    794,025
4                    Atlanta    766,213
5                  San Diego    738,379
...                      ...        ...
1282               Cassville          0
1283  Washington Court House          0
1284          Portola Valley          0
1285                  Amanda          0
1286               Maryville          0

[1286 rows x 2 columns]

#### What's the total dept by state?

In [71]:
res = users.groupby('State')['Total Debt'].sum().reset_index(name = 'Total')
res = res.sort_values(by = 'Total',ascending=False).reset_index(drop=True)
res.index = res.index + 1
res['Total'] = res['Total'].apply(lambda x : f"{x:,.0f}")
res

   State       Total
1     CA  15,977,206
2     TX  10,795,659
3     NY   7,879,461
4     FL   7,427,317
5     IL   5,786,686
6     PA   5,262,359
7     OH   5,092,788
8     NC   4,219,072
9     NJ   4,196,900
10    GA   4,068,584
11    WA   3,621,178
12    MA   3,416,259
13    MI   3,326,231
14    IN   3,179,751
15    MD   3,051,952
16    TN   2,999,158
17    VA   2,892,306
18    AL   2,197,184
19    AZ   2,121,718
20    CT   2,105,428
21    LA   1,850,594
22    WI   1,798,234
23    MO   1,794,306
24    OK   1,766,568
25    KY   1,707,157
26    SC   1,700,650
27    OR   1,698,594
28    MN   1,598,339
29    IA   1,450,283
30    NH   1,257,416
31    CO   1,082,572
32    KS   1,040,001
33    NV     992,681
34    AR     976,684
35    MS     888,738
36    WV     727,812
37    UT     656,194
38    NE     592,875
39    NM     561,379
40    RI     517,705
41    ME     517,646
42    HI     496,356
43    ID     416,920
44    DE     390,918
45    ND     354,050
46    MT     314,934
47    VT     270,915
48    SD     186,296
49    AK     155,300
50    WY      40,074
51    DC           0

#### What's the total yearly income by gender?

In [18]:
res = users.groupby('Gender')['Yearly Income - Person'].sum().reset_index(name = 'Total').sort_values(by = 'Total',ascending=False)
res.index = res.index + 1
res['Total'] = res['Total'].apply(lambda x : f"{x:,.0f}")
res

   Gender       Total
1  Female  46,785,088
2    Male  44,646,676

#### What's the total yearly income by state?

In [69]:
res = users.groupby('State')['Yearly Income - Person'].sum().reset_index(name = 'Total')
res = res.sort_values(by = 'Total',ascending=False).reset_index(drop=True)
res.index = res.index + 1
res['Total'] = res['Total'].apply(lambda x : f"{x:,.0f}")
res

   State       Total
1     CA  11,624,019
2     TX   6,989,662
3     NY   6,498,515
4     FL   5,302,218
5     PA   4,142,936
6     IL   3,872,277
7     OH   3,513,745
8     NJ   3,483,934
9     NC   3,059,313
10    GA   2,898,097
11    MA   2,532,269
12    VA   2,485,873
13    MI   2,472,447
14    WA   2,393,399
15    MD   2,212,532
16    TN   2,101,077
17    IN   1,980,593
18    AZ   1,481,872
19    CT   1,480,940
20    WI   1,446,626
21    MN   1,265,316
22    AL   1,233,181
23    LA   1,220,001
24    KY   1,207,724
25    MO   1,158,547
26    SC   1,125,637
27    OK   1,125,503
28    CO   1,111,806
29    IA   1,061,812
30    OR   1,001,230
31    KS     892,971
32    AR     684,633
33    NV     671,666
34    NH     624,896
35    MS     546,147
36    UT     440,304
37    HI     434,421
38    NM     425,635
39    RI     416,084
40    NE     382,153
41    WV     363,945
42    ME     335,399
43    DE     320,260
44    ID     241,696
45    MT     237,294
46    SD     231,680
47    ND     229,597
48    VT     227,657
49    AK     100,415
50    WY      93,000
51    DC      48,810

#### What's the total yearly income by city?

In [68]:
res = users.groupby('City')['Yearly Income - Person'].sum().reset_index(name = 'Total')
res = res.sort_values(by = 'Total',ascending=False).reset_index(drop=True)
res.index = res.index + 1
res['Total'] = res['Total'].apply(lambda x : f"{x:,.0f}")
res

                 City      Total
1             Houston  1,188,993
2            New York    677,150
3               Miami    652,365
4             Chicago    554,989
5     Fort Lauderdale    528,142
...               ...        ...
1282      Leitchfield      9,445
1283        San Ramon      4,787
1284           Keller      1,788
1285        Princeton        920
1286       Burlingame        645

[1286 rows x 2 columns]

#### Number of users that fico score greater than 550

In [25]:
users[users['FICO Score'] >= 550].shape[0]

1955

### Transactions analysis

#### Number of transactions by year

In [34]:
res = transactions['Year'].value_counts().reset_index(name = 'count').sort_values(by = 'count',ascending=False)
res.index = res.index + 1
res['count'] = res['count'].apply(lambda x : f"{x:,.0f}")
res

    Year  count
1   2018  1,190
2   2014  1,183
3   2015  1,182
4   2017  1,180
5   2004  1,176
6   2012  1,169
7   2019  1,164
8   2008  1,163
9   2013  1,139
10  2005  1,127
11  2010  1,123
12  2006  1,120
13  2009  1,119
14  2016  1,119
15  2011  1,113
16  2007  1,111
17  2003  1,074
18  2002    329
19  2020    182

#### Number  of fraud transaction

In [38]:
transactions[transactions['Is Fraud?'] == 'yes'].shape[0]

0

#### Number of transactions by chip

In [41]:
res = transactions['Use Chip'].value_counts().reset_index(name = 'count').sort_values(by = 'count',ascending=False)
res.index = res.index + 1
res['count'] = res['count'].apply(lambda x : f"{x:,.0f}")
res

             Use Chip   count
1   Swipe Transaction  15,840
2    Chip Transaction   2,808
3  Online Transaction   1,315

#### Total amount per merchant city

In [64]:
res = transactions.groupby('Merchant City')['Amount'].sum().reset_index(name = 'Total')
res = res.sort_values(by = 'Total',ascending=False).reset_index(drop=True)
res.index = res.index + 1
res['Total'] = res['Total'].apply(lambda x : f"{x:,.0f} $")
res

     Merchant City      Total
1         La Verne  887,929 $
2        Mira Loma  193,326 $
3    Monterey Park  178,957 $
4           ONLINE  148,058 $
5           Walnut   12,839 $
..             ...        ...
291         Fossil       11 $
292      Coleville       10 $
293   Williamsburg       10 $
294         Fallon        8 $
295     Walterboro        6 $

[295 rows x 2 columns]

#### What's the total amount per merchant state?

In [63]:
res = transactions.groupby('Merchant State')['Amount'].sum().reset_index(name = 'Total')
res = res.sort_values(by = 'Total',ascending=False).reset_index(drop=True)
res.index = res.index + 1
res['Total'] = res['Total'].apply(lambda x : f"{x:,.0f} $")
res

        Merchant State        Total
1                   CA  1,370,081 $
2                   NJ     13,270 $
3                   TX     10,013 $
4               Mexico      9,518 $
5                   MI      7,903 $
6                   NV      6,931 $
7                   NY      6,843 $
8                   IA      5,689 $
9                   IL      5,326 $
10                  FL      4,829 $
11                  MA      4,429 $
12                  WA      3,453 $
13         Philippines      3,260 $
14             Jamaica      2,706 $
15                  GA      2,510 $
16               Italy      2,371 $
17                  HI      1,892 $
18                  UT      1,861 $
19                  MO      1,293 $
20                  SC      1,261 $
21                  MN      1,006 $
22                  AK        981 $
23               Japan        865 $
24                  PA        782 $
25               China        704 $
26                  AR        654 $
27                  WI        628 $
28                  VA        578 $
29                  OH        522 $
30             Estonia        500 $
31                  NE        390 $
32                  CT        344 $
33                  AZ        338 $
34  Dominican Republic        308 $
35            Portugal        287 $
36         Switzerland        161 $
37              Canada        153 $
38                  NM        152 $
39                  CO        129 $
40                  OR         11 $

#### What's the total amount per year?

In [62]:
res = transactions.groupby('Year')['Amount'].sum().reset_index(name='Total')

res = res.sort_values(by='Total', ascending=False).reset_index(drop=True)

res.index = res.index + 1

res['Total'] = res['Total'].apply(lambda x: f"{x:,.0f} $")

res

    Year     Total
1   2012  99,227 $
2   2008  96,206 $
3   2013  95,969 $
4   2019  94,813 $
5   2004  94,782 $
6   2014  94,229 $
7   2015  93,924 $
8   2007  93,495 $
9   2017  92,938 $
10  2003  92,456 $
11  2005  92,020 $
12  2006  91,881 $
13  2009  91,330 $
14  2018  90,555 $
15  2016  90,047 $
16  2011  89,240 $
17  2010  88,466 $
18  2002  27,891 $
19  2020  13,523 $

#### Number of transactions by errors

In [8]:
res = transactions['Errors?'].value_counts().reset_index(name = 'count')
res = res.sort_values(by = 'count',ascending=False).reset_index(drop=True)
res.index = res.index + 1   
res

                        Errors?  count
1          Insufficient Balance    469
2              Technical Glitch     46
3                       Bad PIN     42
4                Bad Expiration      9
5               Bad Card Number      4
6                       Bad CVV      2
7  Bad PIN,Insufficient Balance      1
8      Bad PIN,Technical Glitch      1